name: Checks

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/checks.yml'
      - '**/*.kts'
      - '**/*.kt'
      - '**/*.properties'
      - '**/*.toml'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - '.github/workflows/checks.yml'
      - '**/*.kts'
      - '**/*.kt'
      - '**/*.properties'
      - '**/*.toml'

jobs:
  publish-kotlin-artifacts:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build kotlin
        run: ./gradlew clean build

      - name: Run wire-ktor-tests
        run: ./gradlew :wire-ktor-tests:jvmTest
