name: Publish

on:
  release:
    types:
      - created

jobs:
  publish-kotlin-artifacts:
    permissions:
      packages: write
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3

        - name: Build kotlin
          run: ./gradlew clean build

        - name: Publish library artifact
          run: ./gradlew publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_VERSION: ${{ github.ref_name }}
