name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the version to be released'
        required: true
        type: string

jobs:
  publish-kotlin-artifacts:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v3

        - name: Build kotlin
          run: ./gradlew clean build

        - name: Publish library artifact
          run: ./gradlew publish
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_VERSION: ${{ inputs.tag }}

        - name: Github Release
          uses: softprops/action-gh-release@v2
          with:
            draft: false
            name: Release ${{ inputs.tag }}
            tag_name: ${{ inputs.tag }}
            target_commitish: ${{ github.ref }}
